services:
  citiesbeen:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - PLAUSIBLE_API_HOST=${PLAUSIBLE_API_HOST}
    container_name: citiesbeen
    restart: unless-stopped
    environment:
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
    ports:
      - '8090:8090'
    volumes:
      - ./citiesbeen/pb_data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      start_period: 5s
      interval: 15s
      timeout: 15s
      retries: 3
